### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by saranonearth** [saranonearth/kanvas19#1]
- [ ] Implement Webpack/Babel

- [ ] Add svg icon to each circle and animate the stroke. (Example - Camera icon for photography event.) [Icon source - Font Awesome or FlatIcons]

- [ ] Website Responsiveness.

- [ ] Add event details on clicking each circle.

- [ ] Close option to close the event details cirlce to click on next event circle. (Animation for event details - https://tobiasahlin.com/moving-letters/ ) [Choose something sexy]

- [ ] Sprinkle some more animation every fucking where possible ;) .
